name: alo_simulator
description: Simulador de alocação de colaboradores.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  intl: ^0.18.0
  google_fonts: ^4.0.3
  image_stack: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Istok Web
      fonts:
        - asset: fonts/IstokWeb-Regular.ttf
        - asset: fonts/IstokWeb-Italic.ttf
          style: italic
        - asset: fonts/IstokWeb-Bold.ttf
          weight: 700
        - asset: fonts/IstokWeb-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/NotoSans-Light.ttf
          weight: 300
        - asset: fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
